---
title: "New Neher Infection Timing Model with Infant tests"
output:
  html_document:
    toc: true
    toc_depth: 2
    dev: 'svg'
---

```{r echo=TRUE, message=FALSE, warning=FALSE, results='hide'}
library(ggplot2)
library(devtools)
library(gridExtra)
library(ggpubr)
library(data.table)
library(Metrics)
library(tidyverse)
library(GGally)

#source("Infant_functions.R")
source("Infant_predict.R")
source("Infant_plotting.R")
source("neher_infant_model.R")

knitr::opts_chunk$set(fig.width=16, fig.height=8)

```

```{r warning=FALSE, results='hide'}
# Set working directory
setwd("/Users/magdalenarussell/Documents/Matsen_group/infection-timing/Infant_Model")

# Load existing data
testing_data = read.csv("../_ignore/AllRunsAvg.csv")
neher_data = read.csv("../_ignore/Neher_data_apd_vl.csv")
colnames(neher_data) = c("Sample", "Time", "Fragment", "APD_1", "APD_5", "APD_10", "VL")
training_data = neher_data
```

```{r echo=TRUE, message=TRUE, warning=FALSE}
for (ty in c("LM_neher")){
    together = compile_data_neher(train_data = training_data, new_data = training_data, apd = 1, type = ty, cohort = 'neher')
    together_infant = compile_data_neher(train_data = testing_data, new_data = testing_data, apd = 1, type = ty, cohort = 'infant')
    plot_APD_TI_regression(together, apd = 1, type = ty)
    show_model_statistics(apd = 1, type= ty)
    plot_ETI_TI_regression(together, apd = 1, type = ty)
    plot_APD_TI_regression(together_infant, apd = 1, type = ty)
    plot_ETI_TI_regression(together_infant, apd = 1, type = ty)
}
```